### ISSUE TITLE
check đổi mật khẩu admin với user

### ISSUE THREAD

**Issue by ayclqt** [3V2T/WebApp#10]
Admin:<img width="960" alt="image" src="https://github.com/3V2T/WebApp/assets/93394403/59fb0339-5f94-44ff-948f-275fb38386c5">
User sau khi đổi: <img width="960" alt="image" src="https://github.com/3V2T/WebApp/assets/93394403/8750a877-3597-4b28-9662-0b29a3342cdf">

**Comment by DKVI** [comment]
đã fix
